// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.api.contract.reply;

import br.ufu.sd.core.grpc.abstracts.SalvarReplyOrBuilder;

/**
 * Protobuf type {@code grpc.SalvarReply}
 */
public final class SalvarReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.SalvarReply)
    SalvarReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SalvarReply.newBuilder() to construct.
  private SalvarReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SalvarReply() {
    exito_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SalvarReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SalvarReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            exito_ = rawValue;
            break;
          }
          case 18: {
            br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder subBuilder = null;
            if (objeto_ != null) {
              subBuilder = objeto_.toBuilder();
            }
            objeto_ = input.readMessage(br.ufu.sd.core.grpc.model.ObjetoConsultado.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(objeto_);
              objeto_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufu.sd.api.contract.reply.SalvarReply.class, br.ufu.sd.api.contract.reply.SalvarReply.Builder.class);
  }

  public static final int EXITO_FIELD_NUMBER = 1;
  private int exito_;
  /**
   * <code>.grpc.Exito exito = 1;</code>
   * @return The enum numeric value on the wire for exito.
   */
  @java.lang.Override public int getExitoValue() {
    return exito_;
  }
  /**
   * <code>.grpc.Exito exito = 1;</code>
   * @return The exito.
   */
  @java.lang.Override public br.ufu.sd.core.grpc.model.Exito getExito() {
    @SuppressWarnings("deprecation")
    br.ufu.sd.core.grpc.model.Exito result = br.ufu.sd.core.grpc.model.Exito.valueOf(exito_);
    return result == null ? br.ufu.sd.core.grpc.model.Exito.UNRECOGNIZED : result;
  }

  public static final int OBJETO_FIELD_NUMBER = 2;
  private br.ufu.sd.core.grpc.model.ObjetoConsultado objeto_;
  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   * @return Whether the objeto field is set.
   */
  @java.lang.Override
  public boolean hasObjeto() {
    return objeto_ != null;
  }
  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   * @return The objeto.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.ObjetoConsultado getObjeto() {
    return objeto_ == null ? br.ufu.sd.core.grpc.model.ObjetoConsultado.getDefaultInstance() : objeto_;
  }
  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder getObjetoOrBuilder() {
    return getObjeto();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exito_ != br.ufu.sd.core.grpc.model.Exito.SUCCESS.getNumber()) {
      output.writeEnum(1, exito_);
    }
    if (objeto_ != null) {
      output.writeMessage(2, getObjeto());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exito_ != br.ufu.sd.core.grpc.model.Exito.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, exito_);
    }
    if (objeto_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getObjeto());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufu.sd.api.contract.reply.SalvarReply)) {
      return super.equals(obj);
    }
    br.ufu.sd.api.contract.reply.SalvarReply other = (br.ufu.sd.api.contract.reply.SalvarReply) obj;

    if (exito_ != other.exito_) return false;
    if (hasObjeto() != other.hasObjeto()) return false;
    if (hasObjeto()) {
      if (!getObjeto()
          .equals(other.getObjeto())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXITO_FIELD_NUMBER;
    hash = (53 * hash) + exito_;
    if (hasObjeto()) {
      hash = (37 * hash) + OBJETO_FIELD_NUMBER;
      hash = (53 * hash) + getObjeto().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.reply.SalvarReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufu.sd.api.contract.reply.SalvarReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.SalvarReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.SalvarReply)
      br.ufu.sd.core.grpc.abstracts.SalvarReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufu.sd.api.contract.reply.SalvarReply.class, br.ufu.sd.api.contract.reply.SalvarReply.Builder.class);
    }

    // Construct using br.ufu.sd.core.grpc.SalvarReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exito_ = 0;

      if (objetoBuilder_ == null) {
        objeto_ = null;
      } else {
        objeto_ = null;
        objetoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarReply_descriptor;
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.reply.SalvarReply getDefaultInstanceForType() {
      return br.ufu.sd.api.contract.reply.SalvarReply.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.reply.SalvarReply build() {
      br.ufu.sd.api.contract.reply.SalvarReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.reply.SalvarReply buildPartial() {
      br.ufu.sd.api.contract.reply.SalvarReply result = new br.ufu.sd.api.contract.reply.SalvarReply(this);
      result.exito_ = exito_;
      if (objetoBuilder_ == null) {
        result.objeto_ = objeto_;
      } else {
        result.objeto_ = objetoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufu.sd.api.contract.reply.SalvarReply) {
        return mergeFrom((br.ufu.sd.api.contract.reply.SalvarReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufu.sd.api.contract.reply.SalvarReply other) {
      if (other == br.ufu.sd.api.contract.reply.SalvarReply.getDefaultInstance()) return this;
      if (other.exito_ != 0) {
        setExitoValue(other.getExitoValue());
      }
      if (other.hasObjeto()) {
        mergeObjeto(other.getObjeto());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufu.sd.api.contract.reply.SalvarReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufu.sd.api.contract.reply.SalvarReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int exito_ = 0;
    /**
     * <code>.grpc.Exito exito = 1;</code>
     * @return The enum numeric value on the wire for exito.
     */
    @java.lang.Override public int getExitoValue() {
      return exito_;
    }
    /**
     * <code>.grpc.Exito exito = 1;</code>
     * @param value The enum numeric value on the wire for exito to set.
     * @return This builder for chaining.
     */
    public Builder setExitoValue(int value) {
      
      exito_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Exito exito = 1;</code>
     * @return The exito.
     */
    @java.lang.Override
    public br.ufu.sd.core.grpc.model.Exito getExito() {
      @SuppressWarnings("deprecation")
      br.ufu.sd.core.grpc.model.Exito result = br.ufu.sd.core.grpc.model.Exito.valueOf(exito_);
      return result == null ? br.ufu.sd.core.grpc.model.Exito.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.Exito exito = 1;</code>
     * @param value The exito to set.
     * @return This builder for chaining.
     */
    public Builder setExito(br.ufu.sd.core.grpc.model.Exito value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      exito_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Exito exito = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExito() {
      
      exito_ = 0;
      onChanged();
      return this;
    }

    private br.ufu.sd.core.grpc.model.ObjetoConsultado objeto_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.ObjetoConsultado, br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder> objetoBuilder_;
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     * @return Whether the objeto field is set.
     */
    public boolean hasObjeto() {
      return objetoBuilder_ != null || objeto_ != null;
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     * @return The objeto.
     */
    public br.ufu.sd.core.grpc.model.ObjetoConsultado getObjeto() {
      if (objetoBuilder_ == null) {
        return objeto_ == null ? br.ufu.sd.core.grpc.model.ObjetoConsultado.getDefaultInstance() : objeto_;
      } else {
        return objetoBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public Builder setObjeto(br.ufu.sd.core.grpc.model.ObjetoConsultado value) {
      if (objetoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        objeto_ = value;
        onChanged();
      } else {
        objetoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public Builder setObjeto(
        br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder builderForValue) {
      if (objetoBuilder_ == null) {
        objeto_ = builderForValue.build();
        onChanged();
      } else {
        objetoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public Builder mergeObjeto(br.ufu.sd.core.grpc.model.ObjetoConsultado value) {
      if (objetoBuilder_ == null) {
        if (objeto_ != null) {
          objeto_ =
            br.ufu.sd.core.grpc.model.ObjetoConsultado.newBuilder(objeto_).mergeFrom(value).buildPartial();
        } else {
          objeto_ = value;
        }
        onChanged();
      } else {
        objetoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public Builder clearObjeto() {
      if (objetoBuilder_ == null) {
        objeto_ = null;
        onChanged();
      } else {
        objeto_ = null;
        objetoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder getObjetoBuilder() {
      
      onChanged();
      return getObjetoFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder getObjetoOrBuilder() {
      if (objetoBuilder_ != null) {
        return objetoBuilder_.getMessageOrBuilder();
      } else {
        return objeto_ == null ?
            br.ufu.sd.core.grpc.model.ObjetoConsultado.getDefaultInstance() : objeto_;
      }
    }
    /**
     * <code>.grpc.ObjetoConsultado objeto = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.ObjetoConsultado, br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder> 
        getObjetoFieldBuilder() {
      if (objetoBuilder_ == null) {
        objetoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.ObjetoConsultado, br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder>(
                getObjeto(),
                getParentForChildren(),
                isClean());
        objeto_ = null;
      }
      return objetoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.SalvarReply)
  }

  // @@protoc_insertion_point(class_scope:grpc.SalvarReply)
  private static final br.ufu.sd.api.contract.reply.SalvarReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufu.sd.api.contract.reply.SalvarReply();
  }

  public static br.ufu.sd.api.contract.reply.SalvarReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SalvarReply>
      PARSER = new com.google.protobuf.AbstractParser<SalvarReply>() {
    @java.lang.Override
    public SalvarReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SalvarReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SalvarReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SalvarReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufu.sd.api.contract.reply.SalvarReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

