// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

import br.ufu.sd.core.grpc.model.Tipo;

public interface ObjetoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Objeto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Tipo type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.grpc.Tipo type = 1;</code>
   * @return The type.
   */
  br.ufu.sd.core.grpc.model.Tipo getType();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
