// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

import br.ufu.sd.core.grpc.model.BInteger;
import br.ufu.sd.core.grpc.model.Objeto;
import br.ufu.sd.core.grpc.model.TStamp;

public interface SalvarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SalvarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.BInteger key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.grpc.BInteger key = 1;</code>
   * @return The key.
   */
  br.ufu.sd.core.grpc.model.BInteger getKey();
  /**
   * <code>.grpc.BInteger key = 1;</code>
   */
  br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder getKeyOrBuilder();

  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return The timestamp.
   */
  br.ufu.sd.core.grpc.model.TStamp getTimestamp();
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   */
  br.ufu.sd.core.grpc.abstracts.TStampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.grpc.Objeto object = 3;</code>
   * @return Whether the object field is set.
   */
  boolean hasObject();
  /**
   * <code>.grpc.Objeto object = 3;</code>
   * @return The object.
   */
  br.ufu.sd.core.grpc.model.Objeto getObject();
  /**
   * <code>.grpc.Objeto object = 3;</code>
   */
  br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder getObjectOrBuilder();
}
