// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

import br.ufu.sd.core.grpc.model.Exito;
import br.ufu.sd.core.grpc.model.ObjetoConsultado;

public interface SalvarReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SalvarReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Exito exito = 1;</code>
   * @return The enum numeric value on the wire for exito.
   */
  int getExitoValue();
  /**
   * <code>.grpc.Exito exito = 1;</code>
   * @return The exito.
   */
  br.ufu.sd.core.grpc.model.Exito getExito();

  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   * @return Whether the objeto field is set.
   */
  boolean hasObjeto();
  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   * @return The objeto.
   */
  br.ufu.sd.core.grpc.model.ObjetoConsultado getObjeto();
  /**
   * <code>.grpc.ObjetoConsultado objeto = 2;</code>
   */
  br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder getObjetoOrBuilder();
}
