// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

import br.ufu.sd.api.contract.request.SetRequest;
import br.ufu.sd.api.contract.request.SetRequest.BigInt;
import br.ufu.sd.api.contract.request.SetRequest.BigIntOrBuilder;

public interface SetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.SetRequest.BigInt key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.grpc.SetRequest.BigInt key = 1;</code>
   * @return The key.
   */
  br.ufu.sd.api.contract.request.SetRequest.BigInt getKey();
  /**
   * <code>.grpc.SetRequest.BigInt key = 1;</code>
   */
  br.ufu.sd.api.contract.request.SetRequest.BigIntOrBuilder getKeyOrBuilder();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return Whether the objeto field is set.
   */
  boolean hasObjeto();
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return The objeto.
   */
  com.google.protobuf.Struct getObjeto();
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getObjetoOrBuilder();
}
