// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

public interface TStampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.TStamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
