// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.model;

import br.ufu.sd.core.grpc.NoSqlServiceProto;
import br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder;

/**
 * Protobuf type {@code grpc.ObjetoConsultado}
 */
public final class ObjetoConsultado extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.ObjetoConsultado)
    ObjetoConsultadoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ObjetoConsultado.newBuilder() to construct.
  private ObjetoConsultado(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ObjetoConsultado() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ObjetoConsultado();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ObjetoConsultado(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.ufu.sd.core.grpc.model.Versao.Builder subBuilder = null;
            if (versao_ != null) {
              subBuilder = versao_.toBuilder();
            }
            versao_ = input.readMessage(br.ufu.sd.core.grpc.model.Versao.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(versao_);
              versao_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            br.ufu.sd.core.grpc.model.TStamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(br.ufu.sd.core.grpc.model.TStamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            br.ufu.sd.core.grpc.model.Objeto.Builder subBuilder = null;
            if (dados_ != null) {
              subBuilder = dados_.toBuilder();
            }
            dados_ = input.readMessage(br.ufu.sd.core.grpc.model.Objeto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dados_);
              dados_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_ObjetoConsultado_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_ObjetoConsultado_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufu.sd.core.grpc.model.ObjetoConsultado.class, br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder.class);
  }

  public static final int VERSAO_FIELD_NUMBER = 1;
  private br.ufu.sd.core.grpc.model.Versao versao_;
  /**
   * <code>.grpc.Versao versao = 1;</code>
   * @return Whether the versao field is set.
   */
  @java.lang.Override
  public boolean hasVersao() {
    return versao_ != null;
  }
  /**
   * <code>.grpc.Versao versao = 1;</code>
   * @return The versao.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.Versao getVersao() {
    return versao_ == null ? br.ufu.sd.core.grpc.model.Versao.getDefaultInstance() : versao_;
  }
  /**
   * <code>.grpc.Versao versao = 1;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.VersaoOrBuilder getVersaoOrBuilder() {
    return getVersao();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private br.ufu.sd.core.grpc.model.TStamp timestamp_;
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.TStamp getTimestamp() {
    return timestamp_ == null ? br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.TStampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int DADOS_FIELD_NUMBER = 3;
  private br.ufu.sd.core.grpc.model.Objeto dados_;
  /**
   * <code>.grpc.Objeto dados = 3;</code>
   * @return Whether the dados field is set.
   */
  @java.lang.Override
  public boolean hasDados() {
    return dados_ != null;
  }
  /**
   * <code>.grpc.Objeto dados = 3;</code>
   * @return The dados.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.Objeto getDados() {
    return dados_ == null ? br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : dados_;
  }
  /**
   * <code>.grpc.Objeto dados = 3;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder getDadosOrBuilder() {
    return getDados();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (versao_ != null) {
      output.writeMessage(1, getVersao());
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    if (dados_ != null) {
      output.writeMessage(3, getDados());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (versao_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersao());
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (dados_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDados());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufu.sd.core.grpc.model.ObjetoConsultado)) {
      return super.equals(obj);
    }
    br.ufu.sd.core.grpc.model.ObjetoConsultado other = (br.ufu.sd.core.grpc.model.ObjetoConsultado) obj;

    if (hasVersao() != other.hasVersao()) return false;
    if (hasVersao()) {
      if (!getVersao()
          .equals(other.getVersao())) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasDados() != other.hasDados()) return false;
    if (hasDados()) {
      if (!getDados()
          .equals(other.getDados())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersao()) {
      hash = (37 * hash) + VERSAO_FIELD_NUMBER;
      hash = (53 * hash) + getVersao().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasDados()) {
      hash = (37 * hash) + DADOS_FIELD_NUMBER;
      hash = (53 * hash) + getDados().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.core.grpc.model.ObjetoConsultado parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufu.sd.core.grpc.model.ObjetoConsultado prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.ObjetoConsultado}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.ObjetoConsultado)
      br.ufu.sd.core.grpc.abstracts.ObjetoConsultadoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_ObjetoConsultado_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_ObjetoConsultado_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufu.sd.core.grpc.model.ObjetoConsultado.class, br.ufu.sd.core.grpc.model.ObjetoConsultado.Builder.class);
    }

    // Construct using br.ufu.sd.core.grpc.ObjetoConsultado.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (versaoBuilder_ == null) {
        versao_ = null;
      } else {
        versao_ = null;
        versaoBuilder_ = null;
      }
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (dadosBuilder_ == null) {
        dados_ = null;
      } else {
        dados_ = null;
        dadosBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_ObjetoConsultado_descriptor;
    }

    @java.lang.Override
    public br.ufu.sd.core.grpc.model.ObjetoConsultado getDefaultInstanceForType() {
      return br.ufu.sd.core.grpc.model.ObjetoConsultado.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufu.sd.core.grpc.model.ObjetoConsultado build() {
      br.ufu.sd.core.grpc.model.ObjetoConsultado result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufu.sd.core.grpc.model.ObjetoConsultado buildPartial() {
      br.ufu.sd.core.grpc.model.ObjetoConsultado result = new br.ufu.sd.core.grpc.model.ObjetoConsultado(this);
      if (versaoBuilder_ == null) {
        result.versao_ = versao_;
      } else {
        result.versao_ = versaoBuilder_.build();
      }
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (dadosBuilder_ == null) {
        result.dados_ = dados_;
      } else {
        result.dados_ = dadosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufu.sd.core.grpc.model.ObjetoConsultado) {
        return mergeFrom((br.ufu.sd.core.grpc.model.ObjetoConsultado)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufu.sd.core.grpc.model.ObjetoConsultado other) {
      if (other == br.ufu.sd.core.grpc.model.ObjetoConsultado.getDefaultInstance()) return this;
      if (other.hasVersao()) {
        mergeVersao(other.getVersao());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasDados()) {
        mergeDados(other.getDados());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufu.sd.core.grpc.model.ObjetoConsultado parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufu.sd.core.grpc.model.ObjetoConsultado) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private br.ufu.sd.core.grpc.model.Versao versao_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Versao, br.ufu.sd.core.grpc.model.Versao.Builder, br.ufu.sd.core.grpc.abstracts.VersaoOrBuilder> versaoBuilder_;
    /**
     * <code>.grpc.Versao versao = 1;</code>
     * @return Whether the versao field is set.
     */
    public boolean hasVersao() {
      return versaoBuilder_ != null || versao_ != null;
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     * @return The versao.
     */
    public br.ufu.sd.core.grpc.model.Versao getVersao() {
      if (versaoBuilder_ == null) {
        return versao_ == null ? br.ufu.sd.core.grpc.model.Versao.getDefaultInstance() : versao_;
      } else {
        return versaoBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public Builder setVersao(br.ufu.sd.core.grpc.model.Versao value) {
      if (versaoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        versao_ = value;
        onChanged();
      } else {
        versaoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public Builder setVersao(
        br.ufu.sd.core.grpc.model.Versao.Builder builderForValue) {
      if (versaoBuilder_ == null) {
        versao_ = builderForValue.build();
        onChanged();
      } else {
        versaoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public Builder mergeVersao(br.ufu.sd.core.grpc.model.Versao value) {
      if (versaoBuilder_ == null) {
        if (versao_ != null) {
          versao_ =
            br.ufu.sd.core.grpc.model.Versao.newBuilder(versao_).mergeFrom(value).buildPartial();
        } else {
          versao_ = value;
        }
        onChanged();
      } else {
        versaoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public Builder clearVersao() {
      if (versaoBuilder_ == null) {
        versao_ = null;
        onChanged();
      } else {
        versao_ = null;
        versaoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public br.ufu.sd.core.grpc.model.Versao.Builder getVersaoBuilder() {
      
      onChanged();
      return getVersaoFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.VersaoOrBuilder getVersaoOrBuilder() {
      if (versaoBuilder_ != null) {
        return versaoBuilder_.getMessageOrBuilder();
      } else {
        return versao_ == null ?
            br.ufu.sd.core.grpc.model.Versao.getDefaultInstance() : versao_;
      }
    }
    /**
     * <code>.grpc.Versao versao = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Versao, br.ufu.sd.core.grpc.model.Versao.Builder, br.ufu.sd.core.grpc.abstracts.VersaoOrBuilder> 
        getVersaoFieldBuilder() {
      if (versaoBuilder_ == null) {
        versaoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.Versao, br.ufu.sd.core.grpc.model.Versao.Builder, br.ufu.sd.core.grpc.abstracts.VersaoOrBuilder>(
                getVersao(),
                getParentForChildren(),
                isClean());
        versao_ = null;
      }
      return versaoBuilder_;
    }

    private br.ufu.sd.core.grpc.model.TStamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder> timestampBuilder_;
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     * @return The timestamp.
     */
    public br.ufu.sd.core.grpc.model.TStamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder setTimestamp(br.ufu.sd.core.grpc.model.TStamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        br.ufu.sd.core.grpc.model.TStamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(br.ufu.sd.core.grpc.model.TStamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            br.ufu.sd.core.grpc.model.TStamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public br.ufu.sd.core.grpc.model.TStamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.TStampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private br.ufu.sd.core.grpc.model.Objeto dados_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder> dadosBuilder_;
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     * @return Whether the dados field is set.
     */
    public boolean hasDados() {
      return dadosBuilder_ != null || dados_ != null;
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     * @return The dados.
     */
    public br.ufu.sd.core.grpc.model.Objeto getDados() {
      if (dadosBuilder_ == null) {
        return dados_ == null ? br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : dados_;
      } else {
        return dadosBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public Builder setDados(br.ufu.sd.core.grpc.model.Objeto value) {
      if (dadosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dados_ = value;
        onChanged();
      } else {
        dadosBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public Builder setDados(
        br.ufu.sd.core.grpc.model.Objeto.Builder builderForValue) {
      if (dadosBuilder_ == null) {
        dados_ = builderForValue.build();
        onChanged();
      } else {
        dadosBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public Builder mergeDados(br.ufu.sd.core.grpc.model.Objeto value) {
      if (dadosBuilder_ == null) {
        if (dados_ != null) {
          dados_ =
            br.ufu.sd.core.grpc.model.Objeto.newBuilder(dados_).mergeFrom(value).buildPartial();
        } else {
          dados_ = value;
        }
        onChanged();
      } else {
        dadosBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public Builder clearDados() {
      if (dadosBuilder_ == null) {
        dados_ = null;
        onChanged();
      } else {
        dados_ = null;
        dadosBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public br.ufu.sd.core.grpc.model.Objeto.Builder getDadosBuilder() {
      
      onChanged();
      return getDadosFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder getDadosOrBuilder() {
      if (dadosBuilder_ != null) {
        return dadosBuilder_.getMessageOrBuilder();
      } else {
        return dados_ == null ?
            br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : dados_;
      }
    }
    /**
     * <code>.grpc.Objeto dados = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder> 
        getDadosFieldBuilder() {
      if (dadosBuilder_ == null) {
        dadosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder>(
                getDados(),
                getParentForChildren(),
                isClean());
        dados_ = null;
      }
      return dadosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.ObjetoConsultado)
  }

  // @@protoc_insertion_point(class_scope:grpc.ObjetoConsultado)
  private static final br.ufu.sd.core.grpc.model.ObjetoConsultado DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufu.sd.core.grpc.model.ObjetoConsultado();
  }

  public static br.ufu.sd.core.grpc.model.ObjetoConsultado getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ObjetoConsultado>
      PARSER = new com.google.protobuf.AbstractParser<ObjetoConsultado>() {
    @java.lang.Override
    public ObjetoConsultado parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ObjetoConsultado(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ObjetoConsultado> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ObjetoConsultado> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufu.sd.core.grpc.model.ObjetoConsultado getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

