// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.model;

import br.ufu.sd.core.grpc.NoSqlServiceProto;

/**
 * <pre>
 * enumeracao abstraindo o conceito de tipo dado
 * </pre>
 *
 * Protobuf enum {@code grpc.Tipo}
 */
public enum Tipo
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JSON_OBJECT = 0;</code>
   */
  JSON_OBJECT(0),
  /**
   * <code>DATE = 1;</code>
   */
  DATE(1),
  /**
   * <code>DATETIME = 2;</code>
   */
  DATETIME(2),
  /**
   * <code>TIMESTAMP = 3;</code>
   */
  TIMESTAMP(3),
  /**
   * <code>VARCHAR = 4;</code>
   */
  VARCHAR(4),
  /**
   * <code>INT = 5;</code>
   */
  INT(5),
  /**
   * <pre>
   * ... varios outros
   * </pre>
   *
   * <code>FLOAT = 6;</code>
   */
  FLOAT(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JSON_OBJECT = 0;</code>
   */
  public static final int JSON_OBJECT_VALUE = 0;
  /**
   * <code>DATE = 1;</code>
   */
  public static final int DATE_VALUE = 1;
  /**
   * <code>DATETIME = 2;</code>
   */
  public static final int DATETIME_VALUE = 2;
  /**
   * <code>TIMESTAMP = 3;</code>
   */
  public static final int TIMESTAMP_VALUE = 3;
  /**
   * <code>VARCHAR = 4;</code>
   */
  public static final int VARCHAR_VALUE = 4;
  /**
   * <code>INT = 5;</code>
   */
  public static final int INT_VALUE = 5;
  /**
   * <pre>
   * ... varios outros
   * </pre>
   *
   * <code>FLOAT = 6;</code>
   */
  public static final int FLOAT_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Tipo valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Tipo forNumber(int value) {
    switch (value) {
      case 0: return JSON_OBJECT;
      case 1: return DATE;
      case 2: return DATETIME;
      case 3: return TIMESTAMP;
      case 4: return VARCHAR;
      case 5: return INT;
      case 6: return FLOAT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Tipo>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Tipo> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Tipo>() {
          public Tipo findValueByNumber(int number) {
            return Tipo.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Tipo[] VALUES = values();

  public static Tipo valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Tipo(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc.Tipo)
}

