// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

public interface BigIntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.BigInt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
