// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc;

public final class NoSqlServiceProto {
  private NoSqlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SetRequest_descriptor;
  public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SetRequest_fieldAccessorTable;
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SetRequest_BigInt_descriptor;
  public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SetRequest_BigInt_fieldAccessorTable;
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SetReply_descriptor;
  public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SetReply_fieldAccessorTable;
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Valor_descriptor;
  public static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Valor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024nosql_database.proto\022\004grpc\032\034google/pro" +
      "tobuf/struct.proto\"\207\001\n\nSetRequest\022$\n\003key" +
      "\030\001 \001(\0132\027.grpc.SetRequest.BigInt\022\021\n\ttimes" +
      "tamp\030\002 \001(\003\022\'\n\006objeto\030\003 \001(\0132\027.google.prot" +
      "obuf.Struct\032\027\n\006BigInt\022\r\n\005value\030\001 \001(\014\"l\n\010" +
      "SetReply\022#\n\005exito\030\001 \001(\0162\024.grpc.SetReply." +
      "Exito\022\032\n\005valor\030\002 \001(\0132\013.grpc.Valor\"\037\n\005Exi" +
      "to\022\t\n\005ERROR\020\000\022\013\n\007SUCCESS\020\001\"S\n\005Valor\022\016\n\006v" +
      "ersao\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001(\003\022\'\n\006objeto" +
      "\030\003 \001(\0132\027.google.protobuf.Struct29\n\014NoSql" +
      "Service\022)\n\003set\022\020.grpc.SetRequest\032\016.grpc." +
      "SetReply\"\000B*\n\023br.ufu.sd.core.grpcB\021NoSql" +
      "ServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_grpc_SetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_SetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SetRequest_descriptor,
        new java.lang.String[] { "Key", "Timestamp", "Objeto", });
    internal_static_grpc_SetRequest_BigInt_descriptor =
      internal_static_grpc_SetRequest_descriptor.getNestedTypes().get(0);
    internal_static_grpc_SetRequest_BigInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SetRequest_BigInt_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_grpc_SetReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_SetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SetReply_descriptor,
        new java.lang.String[] { "Exito", "Valor", });
    internal_static_grpc_Valor_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_Valor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Valor_descriptor,
        new java.lang.String[] { "Versao", "Timestamp", "Objeto", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
