// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.api.contract.request;

import br.ufu.sd.core.grpc.abstracts.SalvarRequestOrBuilder;

/**
 * Protobuf type {@code grpc.SalvarRequest}
 */
public final class SalvarRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.SalvarRequest)
    SalvarRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SalvarRequest.newBuilder() to construct.
  private SalvarRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SalvarRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SalvarRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SalvarRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.ufu.sd.core.grpc.model.BInteger.Builder subBuilder = null;
            if (key_ != null) {
              subBuilder = key_.toBuilder();
            }
            key_ = input.readMessage(br.ufu.sd.core.grpc.model.BInteger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(key_);
              key_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            br.ufu.sd.core.grpc.model.TStamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(br.ufu.sd.core.grpc.model.TStamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            br.ufu.sd.core.grpc.model.Objeto.Builder subBuilder = null;
            if (object_ != null) {
              subBuilder = object_.toBuilder();
            }
            object_ = input.readMessage(br.ufu.sd.core.grpc.model.Objeto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(object_);
              object_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufu.sd.api.contract.request.SalvarRequest.class, br.ufu.sd.api.contract.request.SalvarRequest.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private br.ufu.sd.core.grpc.model.BInteger key_;
  /**
   * <code>.grpc.BInteger key = 1;</code>
   * @return Whether the key field is set.
   */
  @java.lang.Override
  public boolean hasKey() {
    return key_ != null;
  }
  /**
   * <code>.grpc.BInteger key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.BInteger getKey() {
    return key_ == null ? br.ufu.sd.core.grpc.model.BInteger.getDefaultInstance() : key_;
  }
  /**
   * <code>.grpc.BInteger key = 1;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder getKeyOrBuilder() {
    return getKey();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private br.ufu.sd.core.grpc.model.TStamp timestamp_;
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.TStamp getTimestamp() {
    return timestamp_ == null ? br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.grpc.TStamp timestamp = 2;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.TStampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int OBJECT_FIELD_NUMBER = 3;
  private br.ufu.sd.core.grpc.model.Objeto object_;
  /**
   * <code>.grpc.Objeto object = 3;</code>
   * @return Whether the object field is set.
   */
  @java.lang.Override
  public boolean hasObject() {
    return object_ != null;
  }
  /**
   * <code>.grpc.Objeto object = 3;</code>
   * @return The object.
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.model.Objeto getObject() {
    return object_ == null ? br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : object_;
  }
  /**
   * <code>.grpc.Objeto object = 3;</code>
   */
  @java.lang.Override
  public br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder getObjectOrBuilder() {
    return getObject();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (key_ != null) {
      output.writeMessage(1, getKey());
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    if (object_ != null) {
      output.writeMessage(3, getObject());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (key_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getKey());
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (object_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getObject());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ufu.sd.api.contract.request.SalvarRequest)) {
      return super.equals(obj);
    }
    br.ufu.sd.api.contract.request.SalvarRequest other = (br.ufu.sd.api.contract.request.SalvarRequest) obj;

    if (hasKey() != other.hasKey()) return false;
    if (hasKey()) {
      if (!getKey()
          .equals(other.getKey())) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasObject() != other.hasObject()) return false;
    if (hasObject()) {
      if (!getObject()
          .equals(other.getObject())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKey()) {
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasObject()) {
      hash = (37 * hash) + OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getObject().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ufu.sd.api.contract.request.SalvarRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufu.sd.api.contract.request.SalvarRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.SalvarRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.SalvarRequest)
      br.ufu.sd.core.grpc.abstracts.SalvarRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufu.sd.api.contract.request.SalvarRequest.class, br.ufu.sd.api.contract.request.SalvarRequest.Builder.class);
    }

    // Construct using br.ufu.sd.core.grpc.SalvarRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (keyBuilder_ == null) {
        key_ = null;
      } else {
        key_ = null;
        keyBuilder_ = null;
      }
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (objectBuilder_ == null) {
        object_ = null;
      } else {
        object_ = null;
        objectBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufu.sd.core.grpc.NoSqlServiceProto.internal_static_grpc_SalvarRequest_descriptor;
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.request.SalvarRequest getDefaultInstanceForType() {
      return br.ufu.sd.api.contract.request.SalvarRequest.getDefaultInstance();
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.request.SalvarRequest build() {
      br.ufu.sd.api.contract.request.SalvarRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ufu.sd.api.contract.request.SalvarRequest buildPartial() {
      br.ufu.sd.api.contract.request.SalvarRequest result = new br.ufu.sd.api.contract.request.SalvarRequest(this);
      if (keyBuilder_ == null) {
        result.key_ = key_;
      } else {
        result.key_ = keyBuilder_.build();
      }
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (objectBuilder_ == null) {
        result.object_ = object_;
      } else {
        result.object_ = objectBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufu.sd.api.contract.request.SalvarRequest) {
        return mergeFrom((br.ufu.sd.api.contract.request.SalvarRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufu.sd.api.contract.request.SalvarRequest other) {
      if (other == br.ufu.sd.api.contract.request.SalvarRequest.getDefaultInstance()) return this;
      if (other.hasKey()) {
        mergeKey(other.getKey());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasObject()) {
        mergeObject(other.getObject());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufu.sd.api.contract.request.SalvarRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufu.sd.api.contract.request.SalvarRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private br.ufu.sd.core.grpc.model.BInteger key_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.BInteger, br.ufu.sd.core.grpc.model.BInteger.Builder, br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder> keyBuilder_;
    /**
     * <code>.grpc.BInteger key = 1;</code>
     * @return Whether the key field is set.
     */
    public boolean hasKey() {
      return keyBuilder_ != null || key_ != null;
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     * @return The key.
     */
    public br.ufu.sd.core.grpc.model.BInteger getKey() {
      if (keyBuilder_ == null) {
        return key_ == null ? br.ufu.sd.core.grpc.model.BInteger.getDefaultInstance() : key_;
      } else {
        return keyBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public Builder setKey(br.ufu.sd.core.grpc.model.BInteger value) {
      if (keyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        key_ = value;
        onChanged();
      } else {
        keyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public Builder setKey(
        br.ufu.sd.core.grpc.model.BInteger.Builder builderForValue) {
      if (keyBuilder_ == null) {
        key_ = builderForValue.build();
        onChanged();
      } else {
        keyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public Builder mergeKey(br.ufu.sd.core.grpc.model.BInteger value) {
      if (keyBuilder_ == null) {
        if (key_ != null) {
          key_ =
            br.ufu.sd.core.grpc.model.BInteger.newBuilder(key_).mergeFrom(value).buildPartial();
        } else {
          key_ = value;
        }
        onChanged();
      } else {
        keyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public Builder clearKey() {
      if (keyBuilder_ == null) {
        key_ = null;
        onChanged();
      } else {
        key_ = null;
        keyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public br.ufu.sd.core.grpc.model.BInteger.Builder getKeyBuilder() {
      
      onChanged();
      return getKeyFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder getKeyOrBuilder() {
      if (keyBuilder_ != null) {
        return keyBuilder_.getMessageOrBuilder();
      } else {
        return key_ == null ?
            br.ufu.sd.core.grpc.model.BInteger.getDefaultInstance() : key_;
      }
    }
    /**
     * <code>.grpc.BInteger key = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.BInteger, br.ufu.sd.core.grpc.model.BInteger.Builder, br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder> 
        getKeyFieldBuilder() {
      if (keyBuilder_ == null) {
        keyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.BInteger, br.ufu.sd.core.grpc.model.BInteger.Builder, br.ufu.sd.core.grpc.abstracts.BIntegerOrBuilder>(
                getKey(),
                getParentForChildren(),
                isClean());
        key_ = null;
      }
      return keyBuilder_;
    }

    private br.ufu.sd.core.grpc.model.TStamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder> timestampBuilder_;
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     * @return The timestamp.
     */
    public br.ufu.sd.core.grpc.model.TStamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder setTimestamp(br.ufu.sd.core.grpc.model.TStamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        br.ufu.sd.core.grpc.model.TStamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(br.ufu.sd.core.grpc.model.TStamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            br.ufu.sd.core.grpc.model.TStamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public br.ufu.sd.core.grpc.model.TStamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.TStampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            br.ufu.sd.core.grpc.model.TStamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.grpc.TStamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.TStamp, br.ufu.sd.core.grpc.model.TStamp.Builder, br.ufu.sd.core.grpc.abstracts.TStampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private br.ufu.sd.core.grpc.model.Objeto object_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder> objectBuilder_;
    /**
     * <code>.grpc.Objeto object = 3;</code>
     * @return Whether the object field is set.
     */
    public boolean hasObject() {
      return objectBuilder_ != null || object_ != null;
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     * @return The object.
     */
    public br.ufu.sd.core.grpc.model.Objeto getObject() {
      if (objectBuilder_ == null) {
        return object_ == null ? br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : object_;
      } else {
        return objectBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public Builder setObject(br.ufu.sd.core.grpc.model.Objeto value) {
      if (objectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        object_ = value;
        onChanged();
      } else {
        objectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public Builder setObject(
        br.ufu.sd.core.grpc.model.Objeto.Builder builderForValue) {
      if (objectBuilder_ == null) {
        object_ = builderForValue.build();
        onChanged();
      } else {
        objectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public Builder mergeObject(br.ufu.sd.core.grpc.model.Objeto value) {
      if (objectBuilder_ == null) {
        if (object_ != null) {
          object_ =
            br.ufu.sd.core.grpc.model.Objeto.newBuilder(object_).mergeFrom(value).buildPartial();
        } else {
          object_ = value;
        }
        onChanged();
      } else {
        objectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public Builder clearObject() {
      if (objectBuilder_ == null) {
        object_ = null;
        onChanged();
      } else {
        object_ = null;
        objectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public br.ufu.sd.core.grpc.model.Objeto.Builder getObjectBuilder() {
      
      onChanged();
      return getObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder getObjectOrBuilder() {
      if (objectBuilder_ != null) {
        return objectBuilder_.getMessageOrBuilder();
      } else {
        return object_ == null ?
            br.ufu.sd.core.grpc.model.Objeto.getDefaultInstance() : object_;
      }
    }
    /**
     * <code>.grpc.Objeto object = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder> 
        getObjectFieldBuilder() {
      if (objectBuilder_ == null) {
        objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.core.grpc.model.Objeto, br.ufu.sd.core.grpc.model.Objeto.Builder, br.ufu.sd.core.grpc.abstracts.ObjetoOrBuilder>(
                getObject(),
                getParentForChildren(),
                isClean());
        object_ = null;
      }
      return objectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.SalvarRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.SalvarRequest)
  private static final br.ufu.sd.api.contract.request.SalvarRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufu.sd.api.contract.request.SalvarRequest();
  }

  public static br.ufu.sd.api.contract.request.SalvarRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SalvarRequest>
      PARSER = new com.google.protobuf.AbstractParser<SalvarRequest>() {
    @java.lang.Override
    public SalvarRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SalvarRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SalvarRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SalvarRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ufu.sd.api.contract.request.SalvarRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

