// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.api.contract.request;

import br.ufu.sd.core.grpc.NoSqlServiceProto;
import br.ufu.sd.core.grpc.abstracts.GetRequestOrBuilder;
import br.ufu.sd.domain.model.BigInt;

/**
 * Protobuf type {@code grpc.GetRequest}
 */
public final class GetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.GetRequest)
    GetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRequest.newBuilder() to construct.
  private GetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRequest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.ufu.sd.domain.model.BigInt.Builder subBuilder = null;
            if (chave_ != null) {
              subBuilder = chave_.toBuilder();
            }
            chave_ = input.readMessage(br.ufu.sd.domain.model.BigInt.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chave_);
              chave_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NoSqlServiceProto.internal_static_grpc_GetRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NoSqlServiceProto.internal_static_grpc_GetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetRequest.class, Builder.class);
  }

  public static final int CHAVE_FIELD_NUMBER = 1;
  private br.ufu.sd.domain.model.BigInt chave_;
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   * @return Whether the chave field is set.
   */
  @Override
  public boolean hasChave() {
    return chave_ != null;
  }
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   * @return The chave.
   */
  @Override
  public br.ufu.sd.domain.model.BigInt getChave() {
    return chave_ == null ? br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
  }
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   */
  @Override
  public br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder getChaveOrBuilder() {
    return getChave();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chave_ != null) {
      output.writeMessage(1, getChave());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chave_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChave());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetRequest)) {
      return super.equals(obj);
    }
    GetRequest other = (GetRequest) obj;

    if (hasChave() != other.hasChave()) return false;
    if (hasChave()) {
      if (!getChave()
          .equals(other.getChave())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChave()) {
      hash = (37 * hash) + CHAVE_FIELD_NUMBER;
      hash = (53 * hash) + getChave().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.GetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.GetRequest)
      br.ufu.sd.core.grpc.abstracts.GetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NoSqlServiceProto.internal_static_grpc_GetRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NoSqlServiceProto.internal_static_grpc_GetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetRequest.class, Builder.class);
    }

    // Construct using br.ufu.sd.core.grpc.GetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (chaveBuilder_ == null) {
        chave_ = null;
      } else {
        chave_ = null;
        chaveBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NoSqlServiceProto.internal_static_grpc_GetRequest_descriptor;
    }

    @Override
    public GetRequest getDefaultInstanceForType() {
      return GetRequest.getDefaultInstance();
    }

    @Override
    public GetRequest build() {
      GetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetRequest buildPartial() {
      GetRequest result = new GetRequest(this);
      if (chaveBuilder_ == null) {
        result.chave_ = chave_;
      } else {
        result.chave_ = chaveBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetRequest) {
        return mergeFrom((GetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetRequest other) {
      if (other == GetRequest.getDefaultInstance()) return this;
      if (other.hasChave()) {
        mergeChave(other.getChave());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private br.ufu.sd.domain.model.BigInt chave_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder> chaveBuilder_;
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     * @return Whether the chave field is set.
     */
    public boolean hasChave() {
      return chaveBuilder_ != null || chave_ != null;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     * @return The chave.
     */
    public br.ufu.sd.domain.model.BigInt getChave() {
      if (chaveBuilder_ == null) {
        return chave_ == null ? br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
      } else {
        return chaveBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder setChave(br.ufu.sd.domain.model.BigInt value) {
      if (chaveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chave_ = value;
        onChanged();
      } else {
        chaveBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder setChave(
        br.ufu.sd.domain.model.BigInt.Builder builderForValue) {
      if (chaveBuilder_ == null) {
        chave_ = builderForValue.build();
        onChanged();
      } else {
        chaveBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder mergeChave(br.ufu.sd.domain.model.BigInt value) {
      if (chaveBuilder_ == null) {
        if (chave_ != null) {
          chave_ =
            br.ufu.sd.domain.model.BigInt.newBuilder(chave_).mergeFrom(value).buildPartial();
        } else {
          chave_ = value;
        }
        onChanged();
      } else {
        chaveBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder clearChave() {
      if (chaveBuilder_ == null) {
        chave_ = null;
        onChanged();
      } else {
        chave_ = null;
        chaveBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public BigInt.Builder getChaveBuilder() {
      
      onChanged();
      return getChaveFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder getChaveOrBuilder() {
      if (chaveBuilder_ != null) {
        return chaveBuilder_.getMessageOrBuilder();
      } else {
        return chave_ == null ?
            br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
      }
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder> 
        getChaveFieldBuilder() {
      if (chaveBuilder_ == null) {
        chaveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder>(
                getChave(),
                getParentForChildren(),
                isClean());
        chave_ = null;
      }
      return chaveBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.GetRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.GetRequest)
  private static final GetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetRequest();
  }

  public static GetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetRequest>() {
    @Override
    public GetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

