// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.api.contract.request;

import br.ufu.sd.core.grpc.NoSqlServiceProto;
import br.ufu.sd.core.grpc.abstracts.TestAndSetRequestOrBuilder;
import br.ufu.sd.domain.model.BigInt;

/**
 * Protobuf type {@code grpc.TestAndSetRequest}
 */
public final class TestAndSetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.TestAndSetRequest)
    TestAndSetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestAndSetRequest.newBuilder() to construct.
  private TestAndSetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestAndSetRequest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestAndSetRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestAndSetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.ufu.sd.domain.model.BigInt.Builder subBuilder = null;
            if (chave_ != null) {
              subBuilder = chave_.toBuilder();
            }
            chave_ = input.readMessage(br.ufu.sd.domain.model.BigInt.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chave_);
              chave_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 26: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (objeto_ != null) {
              subBuilder = objeto_.toBuilder();
            }
            objeto_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(objeto_);
              objeto_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            versao_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NoSqlServiceProto.internal_static_grpc_TestAndSetRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NoSqlServiceProto.internal_static_grpc_TestAndSetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TestAndSetRequest.class, Builder.class);
  }

  public static final int CHAVE_FIELD_NUMBER = 1;
  private br.ufu.sd.domain.model.BigInt chave_;
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   * @return Whether the chave field is set.
   */
  @Override
  public boolean hasChave() {
    return chave_ != null;
  }
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   * @return The chave.
   */
  @Override
  public br.ufu.sd.domain.model.BigInt getChave() {
    return chave_ == null ? br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
  }
  /**
   * <code>.grpc.BigInt chave = 1;</code>
   */
  @Override
  public br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder getChaveOrBuilder() {
    return getChave();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int OBJETO_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct objeto_;
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return Whether the objeto field is set.
   */
  @Override
  public boolean hasObjeto() {
    return objeto_ != null;
  }
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return The objeto.
   */
  @Override
  public com.google.protobuf.Struct getObjeto() {
    return objeto_ == null ? com.google.protobuf.Struct.getDefaultInstance() : objeto_;
  }
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   */
  @Override
  public com.google.protobuf.StructOrBuilder getObjetoOrBuilder() {
    return getObjeto();
  }

  public static final int VERSAO_FIELD_NUMBER = 4;
  private long versao_;
  /**
   * <code>int64 versao = 4;</code>
   * @return The versao.
   */
  @Override
  public long getVersao() {
    return versao_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chave_ != null) {
      output.writeMessage(1, getChave());
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (objeto_ != null) {
      output.writeMessage(3, getObjeto());
    }
    if (versao_ != 0L) {
      output.writeInt64(4, versao_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chave_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChave());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (objeto_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getObjeto());
    }
    if (versao_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, versao_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TestAndSetRequest)) {
      return super.equals(obj);
    }
    TestAndSetRequest other = (TestAndSetRequest) obj;

    if (hasChave() != other.hasChave()) return false;
    if (hasChave()) {
      if (!getChave()
          .equals(other.getChave())) return false;
    }
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (hasObjeto() != other.hasObjeto()) return false;
    if (hasObjeto()) {
      if (!getObjeto()
          .equals(other.getObjeto())) return false;
    }
    if (getVersao()
        != other.getVersao()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChave()) {
      hash = (37 * hash) + CHAVE_FIELD_NUMBER;
      hash = (53 * hash) + getChave().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasObjeto()) {
      hash = (37 * hash) + OBJETO_FIELD_NUMBER;
      hash = (53 * hash) + getObjeto().hashCode();
    }
    hash = (37 * hash) + VERSAO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersao());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TestAndSetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TestAndSetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TestAndSetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TestAndSetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TestAndSetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TestAndSetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TestAndSetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TestAndSetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TestAndSetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TestAndSetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TestAndSetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TestAndSetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TestAndSetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.TestAndSetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.TestAndSetRequest)
      br.ufu.sd.core.grpc.abstracts.TestAndSetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NoSqlServiceProto.internal_static_grpc_TestAndSetRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NoSqlServiceProto.internal_static_grpc_TestAndSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestAndSetRequest.class, Builder.class);
    }

    // Construct using br.ufu.sd.core.grpc.TestAndSetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (chaveBuilder_ == null) {
        chave_ = null;
      } else {
        chave_ = null;
        chaveBuilder_ = null;
      }
      timestamp_ = 0L;

      if (objetoBuilder_ == null) {
        objeto_ = null;
      } else {
        objeto_ = null;
        objetoBuilder_ = null;
      }
      versao_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NoSqlServiceProto.internal_static_grpc_TestAndSetRequest_descriptor;
    }

    @Override
    public TestAndSetRequest getDefaultInstanceForType() {
      return TestAndSetRequest.getDefaultInstance();
    }

    @Override
    public TestAndSetRequest build() {
      TestAndSetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TestAndSetRequest buildPartial() {
      TestAndSetRequest result = new TestAndSetRequest(this);
      if (chaveBuilder_ == null) {
        result.chave_ = chave_;
      } else {
        result.chave_ = chaveBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      if (objetoBuilder_ == null) {
        result.objeto_ = objeto_;
      } else {
        result.objeto_ = objetoBuilder_.build();
      }
      result.versao_ = versao_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TestAndSetRequest) {
        return mergeFrom((TestAndSetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TestAndSetRequest other) {
      if (other == TestAndSetRequest.getDefaultInstance()) return this;
      if (other.hasChave()) {
        mergeChave(other.getChave());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasObjeto()) {
        mergeObjeto(other.getObjeto());
      }
      if (other.getVersao() != 0L) {
        setVersao(other.getVersao());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TestAndSetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TestAndSetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private br.ufu.sd.domain.model.BigInt chave_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder> chaveBuilder_;
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     * @return Whether the chave field is set.
     */
    public boolean hasChave() {
      return chaveBuilder_ != null || chave_ != null;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     * @return The chave.
     */
    public br.ufu.sd.domain.model.BigInt getChave() {
      if (chaveBuilder_ == null) {
        return chave_ == null ? br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
      } else {
        return chaveBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder setChave(br.ufu.sd.domain.model.BigInt value) {
      if (chaveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chave_ = value;
        onChanged();
      } else {
        chaveBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder setChave(
        br.ufu.sd.domain.model.BigInt.Builder builderForValue) {
      if (chaveBuilder_ == null) {
        chave_ = builderForValue.build();
        onChanged();
      } else {
        chaveBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder mergeChave(br.ufu.sd.domain.model.BigInt value) {
      if (chaveBuilder_ == null) {
        if (chave_ != null) {
          chave_ =
            br.ufu.sd.domain.model.BigInt.newBuilder(chave_).mergeFrom(value).buildPartial();
        } else {
          chave_ = value;
        }
        onChanged();
      } else {
        chaveBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public Builder clearChave() {
      if (chaveBuilder_ == null) {
        chave_ = null;
        onChanged();
      } else {
        chave_ = null;
        chaveBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public BigInt.Builder getChaveBuilder() {
      
      onChanged();
      return getChaveFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    public br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder getChaveOrBuilder() {
      if (chaveBuilder_ != null) {
        return chaveBuilder_.getMessageOrBuilder();
      } else {
        return chave_ == null ?
            br.ufu.sd.domain.model.BigInt.getDefaultInstance() : chave_;
      }
    }
    /**
     * <code>.grpc.BigInt chave = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder> 
        getChaveFieldBuilder() {
      if (chaveBuilder_ == null) {
        chaveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.ufu.sd.domain.model.BigInt, br.ufu.sd.domain.model.BigInt.Builder, br.ufu.sd.core.grpc.abstracts.BigIntOrBuilder>(
                getChave(),
                getParentForChildren(),
                isClean());
        chave_ = null;
      }
      return chaveBuilder_;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct objeto_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> objetoBuilder_;
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     * @return Whether the objeto field is set.
     */
    public boolean hasObjeto() {
      return objetoBuilder_ != null || objeto_ != null;
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     * @return The objeto.
     */
    public com.google.protobuf.Struct getObjeto() {
      if (objetoBuilder_ == null) {
        return objeto_ == null ? com.google.protobuf.Struct.getDefaultInstance() : objeto_;
      } else {
        return objetoBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public Builder setObjeto(com.google.protobuf.Struct value) {
      if (objetoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        objeto_ = value;
        onChanged();
      } else {
        objetoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public Builder setObjeto(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (objetoBuilder_ == null) {
        objeto_ = builderForValue.build();
        onChanged();
      } else {
        objetoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public Builder mergeObjeto(com.google.protobuf.Struct value) {
      if (objetoBuilder_ == null) {
        if (objeto_ != null) {
          objeto_ =
            com.google.protobuf.Struct.newBuilder(objeto_).mergeFrom(value).buildPartial();
        } else {
          objeto_ = value;
        }
        onChanged();
      } else {
        objetoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public Builder clearObjeto() {
      if (objetoBuilder_ == null) {
        objeto_ = null;
        onChanged();
      } else {
        objeto_ = null;
        objetoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public com.google.protobuf.Struct.Builder getObjetoBuilder() {
      
      onChanged();
      return getObjetoFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    public com.google.protobuf.StructOrBuilder getObjetoOrBuilder() {
      if (objetoBuilder_ != null) {
        return objetoBuilder_.getMessageOrBuilder();
      } else {
        return objeto_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : objeto_;
      }
    }
    /**
     * <code>.google.protobuf.Struct objeto = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getObjetoFieldBuilder() {
      if (objetoBuilder_ == null) {
        objetoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getObjeto(),
                getParentForChildren(),
                isClean());
        objeto_ = null;
      }
      return objetoBuilder_;
    }

    private long versao_ ;
    /**
     * <code>int64 versao = 4;</code>
     * @return The versao.
     */
    @Override
    public long getVersao() {
      return versao_;
    }
    /**
     * <code>int64 versao = 4;</code>
     * @param value The versao to set.
     * @return This builder for chaining.
     */
    public Builder setVersao(long value) {
      
      versao_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 versao = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersao() {
      
      versao_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.TestAndSetRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.TestAndSetRequest)
  private static final TestAndSetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TestAndSetRequest();
  }

  public static TestAndSetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestAndSetRequest>
      PARSER = new com.google.protobuf.AbstractParser<TestAndSetRequest>() {
    @Override
    public TestAndSetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestAndSetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestAndSetRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TestAndSetRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public TestAndSetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

