// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

import br.ufu.sd.api.contract.reply.SetReply;
import br.ufu.sd.api.contract.reply.SetReply.Exito;
import br.ufu.sd.domain.model.Valor;

public interface SetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.SetReply.Exito exito = 1;</code>
   * @return The enum numeric value on the wire for exito.
   */
  int getExitoValue();
  /**
   * <code>.grpc.SetReply.Exito exito = 1;</code>
   * @return The exito.
   */
  br.ufu.sd.api.contract.reply.SetReply.Exito getExito();

  /**
   * <code>.grpc.Valor valor = 2;</code>
   * @return Whether the valor field is set.
   */
  boolean hasValor();
  /**
   * <code>.grpc.Valor valor = 2;</code>
   * @return The valor.
   */
  br.ufu.sd.domain.model.Valor getValor();
  /**
   * <code>.grpc.Valor valor = 2;</code>
   */
  br.ufu.sd.core.grpc.abstracts.ValorOrBuilder getValorOrBuilder();
}
