// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nosql_database.proto

package br.ufu.sd.core.grpc.abstracts;

public interface ValorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Valor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 versao = 1;</code>
   * @return The versao.
   */
  long getVersao();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return Whether the objeto field is set.
   */
  boolean hasObjeto();
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   * @return The objeto.
   */
  com.google.protobuf.Struct getObjeto();
  /**
   * <code>.google.protobuf.Struct objeto = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getObjetoOrBuilder();
}
